### ISSUE TITLE
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: No content to map due to end-of-input

### ISSUE THREAD

**Issue by dada1804** [aws/serverless-java-container#843] opened 2024-04-16 07:33 UTC
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*: `eg. 1.5`

*Implementations:* `Jersey / Spring / Spring Boot / Spring Boot 2 / Spark`

*Framework version:* `eg SpringBoot 2.2.6.RELEASE`

*Frontend service:* `REST API / HTTP API / ALB`

*Deployment method:* `eg SAM, Serverless Framework, Console`

## Scenario
*Describe what you are trying to accomplish*

## Expected behavior
*Describe how you would expect the application to behave*

## Actual behavior
*Describe what you are seeing instead*

## Steps to reproduce
*Provide code samples we can use to reproduce the issue as part of our integration tests. If there is a public repository for the misbehaving application link to it here*

## Full log output
*Paste the full log output from the Lambda function's CloudWatch logs*

```
logs
```

**Comment by deki** [comment] 2024-04-16 07:41
Looks like this is a duplicate of #844?

**Closed** 2024-04-16 09:02 UTC
